### ISSUE TITLE
GraphQLのMutationのdeletePostとupdatePostで"INTERNAL_SERVER_ERROR"が返される

### ISSUE THREAD

**Issue by ReoHakase** [3I-shikosai32/practice-front#2]
# 再現方法
ヘッダーのauthorizationにトークンを設定した状態で以下のMutationを送る。
INTERNAL_SERVER_ERRORのエラー文の通りにidのみを指定すると、GraphQLのスキーマに合致しなくなるためまたエラーが出る。
画像はupdatePostのもののみだが、deletePostでも同様のことが起こる。
![image](https://user-images.githubusercontent.com/16751535/187014866-864768c2-ae20-4160-ae31-a35a493cf159.png)
![image](https://user-images.githubusercontent.com/16751535/187015549-2f333e32-206c-4bd9-9858-501f1b2481d7.png)

**Comment by ReoHakase** [comment]
# おそらくの原因
updatePostとdeletePostのNestJSでのリゾルバの実装[practice-server/src/components/post/post.service.ts](https://github.com/3I-shikosai32/practice-server/blob/main/src/components/post/post.service.ts)で使われている型定義Prisma.PostWhereUniqueInputと、GraphQLのスキーマ側での型PostRelatedUserWhere - [practice-server/schema.gql](https://github.com/3I-shikosai32/practice-server/blob/main/schema.gql)が合致していない
![image](https://user-images.githubusercontent.com/16751535/187016408-fa10c20d-5d43-445e-b3fb-4a4c52f551ec.png)
![image](https://user-images.githubusercontent.com/16751535/187016424-00dd9a34-1011-4a18-aabd-d49ec166b150.png)

**Comment by dino3616** [comment]
実相の関係上mainで対応しました。
問題なさそうであればcloseしてください。
https://github.com/3I-shikosai32/practice-server/commit/e11042323cd7f88352dd3c440ae3e5809aa7be3a

**Comment by ReoHakase** [comment]
正常に動作することが確認しました！したがってCloseします
